export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';

export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const RESET_FORM = 'RESET_FORM';

export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
export const FILL_EDIT_FORM = 'FILL_EDIT_FORM';
